feat: 방 찾기 화면
Do-Farming/do-farming_Front pull request #11
Opened 2024-06-21 08:34 UTC by chaeyeon-yang

### PR Type
- [ ] 화면 작업 (Style, CSS)

## 작업 내용
- closes #6 

## 참고 사항, 첨부 자료 등

![IMG_4091](https://github.com/Do-Farming/do-farming_Front/assets/69382168/d87ae89e-7288-4956-9244-635c531727a5)

2024-06-21 08:36 UTC, quswjdgma83 approved these changes
LGTM

2024-06-21 09:50 UTC, LimEunSang requested changes
1. ExampleScreen.tsx 이름 변경하고 
2. 하단 nav bar에 '방 찾기' 페이지로 이동하기 버튼 넣을 거 아니면 headerShown: false로 바꾸는 게 좋을 거 같습니다!

2024-06-21 13:05 UTC, chaeyeon-yang commented
> 1. ExampleScreen.tsx 이름 변경하고
> 2. 하단 nav bar에 '방 찾기' 페이지로 이동하기 버튼 넣을 거 아니면 headerShown: false로 바꾸는 게 좋을 거 같습니다!

@LimEunSang 네 감사합니다! 정흠님이 올려주신 코드 참고해서 stack navigate까지 하고 나서 commit 다시 할 예정입니다!! 이름도 변경하겠습니다. 그때 다시 한 번 리뷰해주실 있나요 ?

2024-06-23 17:09 UTC, LimEunSang commented
> > 1. ExampleScreen.tsx 이름 변경하고
> > 2. 하단 nav bar에 '방 찾기' 페이지로 이동하기 버튼 넣을 거 아니면 headerShown: false로 바꾸는 게 좋을 거 같습니다!
> 
> @LimEunSang 네 감사합니다! 정흠님이 올려주신 코드 참고해서 stack navigate까지 하고 나서 commit 다시 할 예정입니다!! 이름도 변경하겠습니다. 그때 다시 한 번 리뷰해주실 있나요 ?

넵 알겠습니다!

2024-06-24 02:13 UTC, chaeyeon-yang commented
> > > 1. ExampleScreen.tsx 이름 변경하고
> > > 2. 하단 nav bar에 '방 찾기' 페이지로 이동하기 버튼 넣을 거 아니면 headerShown: false로 바꾸는 게 좋을 거 같습니다!
> > 
> > 
> > @LimEunSang 네 감사합니다! 정흠님이 올려주신 코드 참고해서 stack navigate까지 하고 나서 commit 다시 할 예정입니다!! 이름도 변경하겠습니다. 그때 다시 한 번 리뷰해주실 있나요 ?
> 
> 넵 알겠습니다!

완료했습니다!

2024-06-24 03:58 UTC, LimEunSang approved these changes
LGTM!

2024-06-24 03:59 UTC, merged