Feat/jeongheum/manbogi/#10
Do-Farming/do-farming_Front pull request #12
Opened 2024-06-21 08:55 UTC by quswjdgma83

### PR Type
- [x] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- closes

## 참고 사항, 첨부 자료 등

2024-06-21 09:41 UTC, LimEunSang requested changes
고생했습니다 변변
폴더 구조 바뀌었으니까 pull 이후 conflict 만 해결하면 될 거 같아요

2024-06-21 09:41 UTC, LimEunSang commented on screens/pedometer/pedometerScreen.tsx
> +});
최상위 tag인 View는 Layout을 적용할 예정이라 상관없지만
그 안에 있는 Text는 style.component를 적용하기로 해서
이 부분 pull 한 이후에 conflict 해결하면서 적용하면 될 거 같습니다!

2024-06-25 00:13 UTC, quswjdgma83 commented on screens/pedometer/pedometerScreen.tsx
> +});
넵 확인했습니다

2024-06-25 00:16 UTC, chaeyeon-yang approved these changes
🔥

2024-06-25 00:19 UTC, LimEunSang approved these changes
LGTM

2024-06-25 00:19 UTC, merged