Your commit message
Do-Farming/do-farming_Front pull request #46
Opened 2024-06-28 07:07 UTC by Minjoo-kang123

### PR Type
- [ ] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [ ] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- hana 메인화면 clone코딩

## 참고 사항, 첨부 자료 등

2024-06-28 07:22 UTC, LimEunSang requested changes
고생많으셨습니다.
다른 건 선택사항이고, 더미 데이터만 외부 파일에 정의해서 사용하는 것만 필수로 해주세요!

2024-06-28 07:22 UTC, LimEunSang commented on src/screens/hana/HanaMain.tsx
> +const products2 = [
더미데이터가 하나의 파일 안에 모여있어서 코드가 너무 길어지는데,
mocks 폴더 안에 따로 만드는 게 어떨까요?

2024-06-28 07:22 UTC, LimEunSang commented on src/screens/hana/HanaMain.tsx
> +const Pagination: React.FC<{ length: number; currentIndex: number }> = ({
HanaMain 컴포넌트 외부에 정의된 컴포넌트들은 외부 파일로 따로 정리할 수 있으면 좋을 거 같습니다!

2024-06-28 07:22 UTC, LimEunSang commented on src/screens/hana/HanaMain.tsx
> +const products2 = [
변수명을 product1, product2 보다
saleProduct, waterProduct 처럼 어떤 product인지 예측할 수 있게 작명하면 더 좋을 거 같습니다.

2024-06-28 07:22 UTC, LimEunSang commented on src/screens/hana/HanaMain2.tsx
> +// HomeScreen.js
backup 용도의 파일이면 backup 용도의 파일임을 알 수 있게 "backup"이란 키워드를 붙이거나, 삭제하는 게 좋을 거 같습니다.

2024-07-01 05:23 UTC, LimEunSang commented
1. 로그인 전/후 메인화면을 하나의 component file 에서 작성
2. screen 파일명을 "...Screen.tsx" 이런식으로 작명
3. assets 내 이미지 파일을 저장할 때 폴더 구조 생성
4. 사용하지 않는 코드 삭제

해주시면 좋을 거 같습니다.

(할 게 너무 많다 싶으면 언제든 SOS 할 것)

2024-07-02 06:37 UTC, chaeyeon-yang requested changes
헉.. 고생많으셨습니다!!! 🔥 파일 충돌해결하고 은상님께서 말씀해주신 부분만 수정하면 완벽할 것 같아요

2024-07-03 01:45 UTC, LimEunSang approved these changes
LGTM!

2024-07-03 02:36 UTC, chaeyeon-yang approved these changes

2024-07-03 02:36 UTC, merged