feat: 챗봇 화면 개발, 이미지 생성 샘플화면 개발
Do-Farming/do-farming_Front pull request #62
Opened 2024-07-02 08:31 UTC by quswjdgma83

### PR Type
- [x] 기능 개발 (Feature)
- [ ] 코드 스타일 변경 (Code style update) (formatting, local variables)
- [x] 화면 작업 (Style, CSS)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 버그수정 (Bugfix)
- [ ] 빌드, 배포 관련 변경 (Build, Deploy)
- [ ] 문서 작업 (Docs)
- [ ] 그 외 (ETC)

## 작업 내용
- closes #60 #61

## 참고 사항, 첨부 자료 등
![RPReplay_Final1719907685](https://github.com/Do-Farming/do-farming_Front/assets/111037279/10b4414d-618c-4f02-b7aa-eb33cfbe59ff)
![RPReplay_Final1719908351](https://github.com/Do-Farming/do-farming_Front/assets/111037279/536537b5-994d-4435-b5ea-1ba960f81444)

2024-07-02 10:21 UTC, LimEunSang requested changes
수정해야할 게 있어서 일단 보류
완벽하게 수정되면 머지할 예정

2024-07-02 10:21 UTC, LimEunSang commented on src/screens/chatbot/ChatBotScreen.tsx
> +      console.log(response);
추후 주석처리

2024-07-02 10:21 UTC, LimEunSang commented on src/screens/chatbot/ChatBotScreen.tsx
> +      const response = await axios.get('http://172.16.21.100/api/gpt/chat', {
추후 axios instance 사용하기로 수정

2024-07-02 10:21 UTC, LimEunSang commented on src/screens/ExampleScreen.tsx
> +        onPress={() => navigation.navigate('ChatBot')}
?

2024-07-03 00:16 UTC, quswjdgma83 commented on src/screens/ExampleScreen.tsx
> +        onPress={() => navigation.navigate('ChatBot')}
갈고리? 뭐죠?

2024-07-03 00:17 UTC, rabbitate commented on src/screens/ExampleScreen.tsx
> +        onPress={() => navigation.navigate('ChatBot')}
?

2024-07-03 00:54 UTC, LimEunSang approved these changes
로그인 기능 수정이 시간이 좀 걸릴 거 같네요... 일단 머지합시다

2024-07-03 00:55 UTC, merged